=== chrisjsewell/ipypublish/ipypublish/templates/segment.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "$id": "segment",
    "description": "define segments to insert into a jinja template",
    "type": "object",
    "additionalProperties": true,
    "required": [
        "identifier",
        "description",
        "segments"
    ],
    "properties": {
        "$schema": {
            "type": "string"
        },
        "identifier": {
            "description": "the identification of the segments",
            "type": "string"
        },
        "description": {
            "description": "the purpose of this group of segments",
            "type": "string"
        },
        "segments": {
            "additionalProperties": false,
            "description": "the segments to insert",
            "patternProperties": {
                ".+": {
                    "description": "a segment of the template, each line should be a separate list item",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "overwrite": {
            "description": "a list of segment keys that may overwrite previously defined entries",
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    }
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/ipy-slides_ipypublish.html-tplx.json
{
  "overwrite": [
    "notebook_all",
    "html_body_start",
    "notebook_input_markdown"
  ],
  "$schema": "../../schema/segment.schema.json",
  "identifier": "ipypublish-slides_ipypublish",
  "description": "marks up html with slide tags, based on metadata",
  "segments": {
    "globals": [
      "",
      "{% set slidecolumn = [] %}\"",
      "{% set sliderow = {'len':[]} %}\""
    ],
    "html_body_start": [
      "",
      "<div class=\"reveal\">",
      "<div class=\"slides\">",
      "",
      "{%- if nb.metadata.ipub -%}",
      "{%- if nb.metadata.ipub.titlepage -%}",
      "<section>",
      "{%- if nb.metadata.ipub.titlepage.title -%}",
      "<h1>{{ nb.metadata.ipub.titlepage.title }}</h1>",
      "{%- endif -%}",
      "{%- if nb.metadata.ipub.titlepage.subtitle -%}",
      "<h3>{{ nb.metadata.ipub.titlepage.subtitle }}</h3>",
      "{%- endif -%}",
      "{%- if nb.metadata.ipub.titlepage.author -%}",
      "<b>by {{ nb.metadata.ipub.titlepage.author }}</b>",
      "{%- endif -%}",
      "</section>",
      "{%- endif -%}",
      "{%- endif -%}",
      ""
    ],
    "notebook_all": [
      "",
      "",
      "{%- if cell.metadata.ipyslides == 'skip' -%}",
      "{%- endif -%}",
      "",
      "{%- if cell.metadata.ipyslides == 'notes' -%}",
      "<aside class=\"notes\">",
      "{{ super() }}",
      "</aside>",
      "{%- endif -%}",
      "",
      "{%- if cell.metadata.ipyslides == 'first_cell' -%}",
      "{% if slidecolumn.append('1') %}{% endif %}",
      "{% if sliderow.update({'len':[]}) %}{% endif %}",
      "<section>",
      "{{ super() }}",
      "{%- endif -%}",
      "",
      "{%- if cell.metadata.ipyslides == 'horizontalbreak_before' -%}",
      "{{ super() }}",
      "</section>",
      "</section>",
      "{%- endif -%}",
      "",
      "",
      "{%- if cell.metadata.ipyslides == 'horizontalbreak_after_novertical' -%}",
      "{% if slidecolumn.append('1') %}{% endif %}",
      "{% if sliderow.update({'len':[]}) %}{% endif %}",
      "<section>",
      "{{ super() }}",
      "</section>",
      "{%- endif -%}",
      "",
      "{%- if cell.metadata.ipyslides == 'horizontalbreak_after_plusvertical' -%}",
      "{% if slidecolumn.append('1') %}{% endif %}",
      "{% if sliderow.update({'len':[]}) %}{% endif %}",
      "<section>",
      "<section>",
      "{{ super() }}",
      "</section>",
      "<section>",
      "{%- endif -%}",
      "",
      "{%- if cell.metadata.ipyslides == 'horizontalbreak_after' -%}",
      "{% if slidecolumn.append('1') %}{% endif %}",
      "{% if sliderow.update({'len':[]}) %}{% endif %}",
      "<section>",
      "<section>",
      "{{ super() }}",
      "{%- endif -%}",
      "",
      "",
      "{%- if cell.metadata.ipyslides == 'normal' -%}",
      "{{ super() }}",
      "{%- endif -%}",
      "",
      "{%- if cell.metadata.ipyslides == 'verticalbreak_after' -%}",
      "{% if sliderow['len'].append('1') %}{% endif %}",
      "</section>",
      "<section>",
      "{{ super() }}",
      "{%- endif -%}",
      "",
      "{%- if cell.metadata.ipyslides == 'last_cell' -%}",
      "{{ super() }}",
      "</section>",
      "</section>",
      "{%- endif -%}",
      "",
      ""
    ],
    "notebook_input_markdown": [
      "",
      "{{ cell.source  | markdown2html | strip_files_prefix }}"
    ]
  }
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/std-slides.html-tplx.json
{
  "overwrite": [
    "notebook_all"
  ],
  "$schema": "../../schema/segment.schema.json",
  "identifier": "standard-slides",
  "description": "marks up html with slide tags, based on metadata",
  "segments": {
    "html_header": [
      "",
      "",
      "<meta http-equiv=\"X-UA-Compatible\" content=\"chrome=1\" />",
      "",
      "<meta name=\"apple-mobile-web-app-capable\" content=\"yes\" />",
      "<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\" />",
      "",
      "<title>{{resources['metadata']['name']}} slides</title>",
      "",
      "<script src=\"{{resources.reveal.require_js_url}}\"></script>",
      "<script src=\"{{resources.reveal.jquery_url}}\"></script>",
      "",
      "<!-- General and theme style sheets -->",
      "<link rel=\"stylesheet\" href=\"{{resources.reveal.url_prefix}}/css/reveal.css\">",
      "<link rel=\"stylesheet\" href=\"{{resources.reveal.url_prefix}}/css/theme/{{resources.reveal.theme}}.css\" id=\"theme\">",
      "",
      "<!-- If the query includes 'print-pdf', include the PDF print sheet -->",
      "<script>",
      "if( window.location.search.match( /print-pdf/gi ) ) {",
      "        var link = document.createElement( 'link' );",
      "        link.rel = 'stylesheet';",
      "        link.type = 'text/css';",
      "        link.href = '{{resources.reveal.url_prefix}}/css/print/pdf.css';",
      "        document.getElementsByTagName( 'head' )[0].appendChild( link );",
      "}",
      "",
      "</script>",
      "",
      "<!--[if lt IE 9]>",
      "<script src=\"{{resources.reveal.url_prefix}}/lib/js/html5shiv.js\"></script>",
      "<![endif]-->",
      "",
      "<!-- Get Font-awesome from cdn -->",
      "<link rel=\"stylesheet\" href=\"{{resources.reveal.font_awesome_url}}\">",
      "",
      "{% for css in resources.inlining.css -%}",
      "    <style type=\"text/css\">",
      "    {{ css }}",
      "    </style>",
      "{% endfor %}",
      "",
      "<style type=\"text/css\">",
      "/* Overrides of notebook CSS for static HTML export */",
      ".reveal {",
      "  font-size: 160%;",
      "  overflow-y: scroll;",
      "}",
      ".reveal pre {",
      "  width: inherit;",
      "  padding: 0.4em;",
      "  margin: 0px;",
      "  font-family: monospace, sans-serif;",
      "  font-size: 80%;",
      "  box-shadow: 0px 0px 0px rgba(0, 0, 0, 0);",
      "}",
      ".reveal pre code {",
      "  padding: 0px;",
      "}",
      ".reveal section img {",
      "  border: 0px solid black;",
      "  box-shadow: 0 0 10px rgba(0, 0, 0, 0);",
      "}",
      ".reveal i {",
      "  font-style: normal;",
      "  font-family: FontAwesome;",
      "  font-size: 2em;",
      "}",
      ".reveal .slides {",
      "  text-align: left;",
      "}",
      ".reveal.fade {",
      "  opacity: 1;",
      "}",
      ".reveal .progress {",
      "  position: static;",
      "}",
      "div.input_area {",
      "  padding: 0.06em;",
      "}",
      "div.code_cell {",
      "  background-color: transparent;",
      "}",
      "div.prompt {",
      "  width: 11ex;",
      "  padding: 0.4em;",
      "  margin: 0px;",
      "  font-family: monospace, sans-serif;",
      "  font-size: 80%;",
      "  text-align: right;",
      "}",
      "div.output_area pre {",
      "  font-family: monospace, sans-serif;",
      "  font-size: 80%;",
      "}",
      "div.output_prompt {",
      "  /* 5px right shift to account for margin in parent container */",
      "  margin: 5px 5px 0 0;",
      "}",
      "div.text_cell.rendered .rendered_html {",
      "  /* The H1 height seems miscalculated, we are just hidding the scrollbar */",
      "  overflow-y: hidden;",
      "}",
      "a.anchor-link {",
      "  /* There is still an anchor, we are only hidding it */",
      "  display: none;",
      "}",
      ".rendered_html p {",
      "  text-align: inherit;",
      "}",
      "</style>",
      ""
    ],
    "html_body_start": [
      "",
      "<div class=\"reveal\">",
      "<div class=\"slides\">",
      "<section>"
    ],
    "html_body_end": [
      "",
      "</section>",
      "</div>",
      "</div>",
      "",
      "<script>",
      "",
      "require(",
      "    {",
      "      // it makes sense to wait a little bit when you are loading",
      "      // reveal from a cdn in a slow connection environment",
      "      waitSeconds: 15",
      "    },",
      "    [",
      "      \"{{resources.reveal.url_prefix}}/lib/js/head.min.js\",",
      "      \"{{resources.reveal.url_prefix}}/js/reveal.js\"",
      "    ],",
      "",
      "    function(head, Reveal){",
      "",
      "        // Full list of configuration options available here: https://github.com/hakimel/reveal.js#configuration",
      "        Reveal.initialize({",
      "            controls: true,",
      "            progress: true,",
      "            history: true,",
      "",
      "            theme: Reveal.getQueryHash().theme, // available themes are in /css/theme",
      "            transition: Reveal.getQueryHash().transition || 'linear', // default/cube/page/concave/zoom/linear/none",
      "",
      "            // Optional libraries used to extend on reveal.js",
      "            dependencies: [",
      "                { src: \"{{resources.reveal.url_prefix}}/lib/js/classList.js\",",
      "                  condition: function() { return !document.body.classList; } },",
      "                { src: \"{{resources.reveal.url_prefix}}/plugin/notes/notes.js\",",
      "                  async: true,",
      "                  condition: function() { return !!document.body.classList; } }",
      "            ]",
      "        });",
      "",
      "        var update = function(event){",
      "          if(MathJax.Hub.getAllJax(Reveal.getCurrentSlide())){",
      "            MathJax.Hub.Rerender(Reveal.getCurrentSlide());",
      "          }",
      "        };",
      "",
      "        Reveal.addEventListener('slidechanged', update);",
      "",
      "        var update_scroll = function(event){",
      "          $(\".reveal\").scrollTop(0);",
      "        };",
      "",
      "        Reveal.addEventListener('slidechanged', update_scroll);",
      "        Reveal.configure({ slideNumber: 'c/t' });",
      "    }",
      ");",
      "</script>"
    ],
    "notebook_all": [
      "",
      "{%- if cell.metadata.get('slide_start', False) -%}",
      "<section>",
      "{%- endif -%}",
      "{%- if cell.metadata.get('subslide_start', False) -%}",
      "<section>",
      "{%- endif -%}",
      "{%- if cell.metadata.get('fragment_start', False) -%}",
      "<div class=\"fragment\">",
      "{%- endif -%}",
      "",
      "{%- if cell.metadata.slide_type == 'notes' -%}",
      "<aside class=\"notes\">",
      "{{ super() }}",
      "</aside>",
      "{%- elif cell.metadata.slide_type == 'skip' -%}",
      "{%- else -%}",
      "{{ super() }}",
      "{%- endif -%}",
      "",
      "{%- if cell.metadata.get('fragment_end', False) -%}",
      "</div>",
      "{%- endif -%}",
      "{%- if cell.metadata.get('subslide_end', False) -%}",
      "</section>",
      "{%- endif -%}",
      "{%- if cell.metadata.get('slide_end', False) -%}",
      "</section>",
      "{%- endif -%}"
    ]
  }
}
