=== chrisjsewell/ipypublish/ipypublish/templates/outline_schemas/html_tpl_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "$id": "html-tpl",
    "description": "define segments to insert into a jinja template of id html-tpl",
    "outline": {
        "module": "ipypublish.templates.outline_schemas",
        "file": "html_outline.html.j2"
    },
    "type": "object",
    "additionalProperties": false,
    "definitions": {
        "append_before": {
            "description": "a segment of the template, each line should be a separate list item",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "append_after": {
            "description": "a segment of the template, each line should be a separate list item",
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "description",
        "identifier",
        "template",
        "segments"
    ],
    "properties": {
        "$schema": {
            "type": "string"
        },
        "identifier": {
            "description": "the identification of the segments",
            "type": "string"
        },
        "description": {
            "description": "the purpose of this group of segments",
            "type": "string"
        },
        "template": {
            "description": "the template identifier",
            "enum": [
                "html-tpl"
            ]
        },
        "segments": {
            "additionalProperties": false,
            "description": "the segments to insert",
            "properties": {
                "globals": {
                    "description": "inserted at the beginning of the template",
                    "$ref": "#/definitions/append_after"
                },
                "html_header": {
                    "$ref": "#/definitions/append_after"
                },
                "html_body_start": {
                    "$ref": "#/definitions/append_after"
                },
                "html_body_end": {
                    "$ref": "#/definitions/append_after"
                },
                "html_footer": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_all": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_code_prompt": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_code": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_raw": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_markdown": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_unknown": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_code_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_input_raw_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_input_markdown_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_input_unknown_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_input_code_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_raw_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_markdown_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_unknown_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_prompt": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_text": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_error": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_traceback": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_stream_stderr": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_stream_stdout": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_latex": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_markdown": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_png": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_jpg": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_svg": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_pdf": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_html": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_javascript": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_widget_state": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_widget_view": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_text_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_error_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_traceback_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_stream_stderr_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_stream_stdout_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_latex_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_markdown_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_png_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_jpg_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_svg_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_pdf_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_html_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_javascript_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_widget_state_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_widget_view_pre": {
                    "$ref": "#/definitions/append_before"
                },
                "notebook_output_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_text_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_error_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_traceback_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_stream_stderr_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_stream_stdout_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_latex_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_markdown_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_png_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_jpg_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_svg_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_pdf_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_html_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_javascript_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_widget_state_post": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_widget_view_post": {
                    "$ref": "#/definitions/append_after"
                },
                "jinja_macros": {
                    "$ref": "#/definitions/append_after"
                }
            }
        },
        "overwrite": {
            "description": "a list of segment keys that may overwrite previously defined entries",
            "type": "array",
            "items": {
                "enum": [
                    "globals",
                    "html_header",
                    "html_body_start",
                    "html_body_end",
                    "html_footer",
                    "notebook_all",
                    "notebook_input_code_prompt",
                    "notebook_input_code",
                    "notebook_input_raw",
                    "notebook_input_markdown",
                    "notebook_input_unknown",
                    "notebook_input_code_pre",
                    "notebook_input_raw_pre",
                    "notebook_input_markdown_pre",
                    "notebook_input_unknown_pre",
                    "notebook_input_code_post",
                    "notebook_input_raw_post",
                    "notebook_input_markdown_post",
                    "notebook_input_unknown_post",
                    "notebook_output",
                    "notebook_output_prompt",
                    "notebook_output_text",
                    "notebook_output_error",
                    "notebook_output_traceback",
                    "notebook_output_stream_stderr",
                    "notebook_output_stream_stdout",
                    "notebook_output_latex",
                    "notebook_output_markdown",
                    "notebook_output_png",
                    "notebook_output_jpg",
                    "notebook_output_svg",
                    "notebook_output_pdf",
                    "notebook_output_html",
                    "notebook_output_javascript",
                    "notebook_output_widget_state",
                    "notebook_output_widget_view",
                    "notebook_output_pre",
                    "notebook_output_text_pre",
                    "notebook_output_error_pre",
                    "notebook_output_traceback_pre",
                    "notebook_output_stream_stderr_pre",
                    "notebook_output_stream_stdout_pre",
                    "notebook_output_latex_pre",
                    "notebook_output_markdown_pre",
                    "notebook_output_png_pre",
                    "notebook_output_jpg_pre",
                    "notebook_output_svg_pre",
                    "notebook_output_pdf_pre",
                    "notebook_output_html_pre",
                    "notebook_output_javascript_pre",
                    "notebook_output_widget_state_pre",
                    "notebook_output_widget_view_pre",
                    "notebook_output_post",
                    "notebook_output_text_post",
                    "notebook_output_error_post",
                    "notebook_output_traceback_post",
                    "notebook_output_stream_stderr_post",
                    "notebook_output_stream_stdout_post",
                    "notebook_output_latex_post",
                    "notebook_output_markdown_post",
                    "notebook_output_png_post",
                    "notebook_output_jpg_post",
                    "notebook_output_svg_post",
                    "notebook_output_pdf_post",
                    "notebook_output_html_post",
                    "notebook_output_javascript_post",
                    "notebook_output_widget_state_post",
                    "notebook_output_widget_view_post",
                    "jinja_macros"
                ]
            }
        }
    }
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/ipy-slides_mkdown.html-tplx.json
{
  "overwrite": [
    "notebook_all",
    "notebook_input_markdown"
  ],
  "$schema": "../outline_schema/html_tpl_schema.json",
  "identifier": "ipypublish-slides_mkdown",
  "description": "sets markdown main titles (with one #) as their own slides,\nremove code cells ",
  "segments": {
    "globals": [
      "",
      "{% set slidecolumn = [] %}\"",
      "{% set sliderow = {} %}\""
    ],
    "notebook_all": [
      "{{ super() }}"
    ],
    "notebook_input_markdown_pre": [
      "",
      "{%- if cell.source[0] == '#' -%}",
      "    {%- if cell.source[1] == '#' -%}",
      "        {%- if cell.source[2] == '#' -%}",
      "",
      "        {%- else -%}",
      "            {% if slidecolumn | length != 0 %}",
      "</section>",
      "<section>",
      "            {%- endif -%}",
      "            {% if slidecolumn.append('1') %}{% endif %}",
      "        {%- endif -%}",
      "    {%- else -%}",
      "            {% if slidecolumn | length != 0 %}",
      "</section>",
      "<section>",
      "            {%- endif -%}",
      "           {% if slidecolumn.append('1') %}{% endif %}",
      "    {%- endif -%}",
      "{%- endif -%}"
    ],
    "notebook_input_markdown": [
      "",
      "{{ cell.source  | markdown2html | strip_files_prefix }}"
    ]
  },
  "template": "html-tpl"
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/ipy-flexbox_css.html-tplx.json
{
  "$schema": "../outline_schema/html_tpl_schema.json",
  "identifier": "ipypublish-flexbox_css",
  "description": " adds flex boxes (https://github.com/Munawwar/flex-helper)  ",
  "segments": {
    "html_header": [
      "",
      "",
      "<style type=\"text/css\">",
      "/*Stack child items vertically*/",
      ".vbox {",
      "    display: flex;",
      "",
      "    /*Align children vetically*/",
      "    flex-direction: column;",
      "    align-content: flex-start;",
      "",
      "    overflow: hidden; /*Prevent extending beyond boundaries*/",
      "}",
      "/*Stack child items horizontally*/",
      ".hbox {",
      "    display: flex;",
      "",
      "    /*Align children horizontally*/",
      "    flex-direction: row;",
      "    align-content: flex-start;",
      "",
      "    /*Wrap items to next line on main-axis*/",
      "    flex-wrap: wrap;",
      "",
      "    overflow: hidden; /*Prevent extending beyond boundaries*/",
      "}",
      "/*Stretch item along parent's main-axis*/",
      ".flex {",
      "    flex: 1;",
      "}",
      "",
      "/*Stretch item along parent's cross-axis Overrides any cross-* class of parent*/",
      ".stretch-self {",
      "    align-self: stretch;",
      "}",
      "/*Center item along parent's cross-axis. Overrides any cross-* class of parent*/",
      ".center-self {",
      "    align-self: center;",
      "}",
      "",
      "/*Stack child items to the main-axis start*/",
      ".main-start {",
      "    justify-content: flex-start;",
      "}",
      "/*Stack child items to the cross-axis start*/",
      ".cross-start {",
      "    align-items: flex-start;",
      "    align-content: flex-start;",
      "}",
      "/*Stack child items to the main-axis center*/",
      ".main-center {",
      "    justify-content: center;",
      "}",
      "/*Stack child items to the cross-axis center*/",
      ".cross-center {",
      "    align-items: center;",
      "    align-content: center;",
      "}",
      "/*Stack child items to the main-axis end.*/",
      ".main-end {",
      "    justify-content: flex-end;",
      "}",
      "/*Stack child items to the cross-axis end.*/",
      ".cross-end {",
      "    align-items: flex-end;",
      "    align-content: flex-end;",
      "}",
      "/*Stretch child items along the cross-axis*/",
      ".cross-stretch {",
      "    align-items: stretch;",
      "    align-content: stretch;",
      "}",
      "",
      "/*Wrap items to next line on main-axis*/",
      ".wrap {",
      "    flex-wrap: wrap;",
      "}",
      "/*Don't wrap items to next line on main-axis*/",
      ".nowrap {",
      "    flex-wrap: nowrap;",
      "}",
      "",
      "</style>"
    ]
  },
  "template": "html-tpl"
}
