=== chrisjsewell/ipypublish/ipypublish/templates/outline_schemas/latex_tplx_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "$id": "latex-tplx",
    "description": "define segments to insert into the the template jinja template of id latex-tplx",
    "outline": {
        "module": "ipypublish.templates.outline_schemas",
        "file": "latex_outline.latex.j2"
    },
    "type": "object",
    "additionalProperties": false,
    "definitions": {
        "append_after": {
            "description": "a segment of the template, each line should be a separate item",
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "description",
        "identifier",
        "template",
        "segments"
    ],
    "properties": {
        "$schema": {
            "type": "string"
        },
        "identifier": {
            "description": "the identification of the segments",
            "type": "string"
        },
        "description": {
            "description": "the purpose of this group of segments",
            "type": "string"
        },
        "template": {
            "description": "the template identifier",
            "enum": ["latex-tplx"]
        },
        "segments": {
            "additionalProperties": false,
            "description": "the segments to insert",
            "properties": {
                "document_docclass": {
                    "$ref": "#/definitions/append_after"
                },
                "document_packages": {
                    "$ref": "#/definitions/append_after"
                },
                "document_definitions": {
                    "$ref": "#/definitions/append_after"
                },
                "document_margins": {
                    "$ref": "#/definitions/append_after"
                },
                "document_commands": {
                    "$ref": "#/definitions/append_after"
                },
                "document_header_end": {
                    "$ref": "#/definitions/append_after"
                },
                "document_title": {
                    "$ref": "#/definitions/append_after"
                },
                "document_abstract": {
                    "$ref": "#/definitions/append_after"
                },
                "document_predoc": {
                    "$ref": "#/definitions/append_after"
                },
                "document_bibliography": {
                    "$ref": "#/definitions/append_after"
                },
                "document_postdoc": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_code": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_raw": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_markdown": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_input_unknown": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_text": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_error": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_traceback": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_stream": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_latex": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_markdown": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_png": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_jpg": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_svg": {
                    "$ref": "#/definitions/append_after"
                },
                "notebook_output_pdf": {
                    "$ref": "#/definitions/append_after"
                },
                "jinja_macros": {
                    "$ref": "#/definitions/append_after"
                }
            }
        },
        "overwrite": {
            "description": "a list of segment keys that may overwrite previously defined entries",
            "type": "array",
            "items": {
                "enum": [
                    "meta_docstring",
                    "document_docclass",
                    "document_packages",
                    "document_definitions",
                    "document_margins",
                    "document_commands",
                    "document_header_end",
                    "document_title",
                    "document_abstract",
                    "document_predoc",
                    "document_bibliography",
                    "document_postdoc",
                    "notebook_input",
                    "notebook_input_code",
                    "notebook_input_raw",
                    "notebook_input_markdown",
                    "notebook_input_unknown",
                    "notebook_output",
                    "notebook_output_text",
                    "notebook_output_error",
                    "notebook_output_traceback",
                    "notebook_output_stream",
                    "notebook_output_latex",
                    "notebook_output_markdown",
                    "notebook_output_png",
                    "notebook_output_jpg",
                    "notebook_output_svg",
                    "notebook_output_pdf",
                    "jinja_macros"
                ]
            }
        }
    }
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/ipy-contents_framed_code.latex-tpl.json
{
  "$schema": "../outline_schema/latex_tplx_schema.json",
  "identifier": "ipypublish-contents_framed_code",
  "description": "with the input code wrapped and framed",
  "segments": {
    "document_packages": [
      "",
      "",
      "    % define a code float",
      "    \\usepackage{newfloat} % to define a new float types",
      "    \\DeclareFloatingEnvironment[",
      "        fileext=frm,placement={!ht},",
      "        within=section,name=Code]{codecell}",
      "    \\DeclareFloatingEnvironment[",
      "        fileext=frm,placement={!ht},",
      "        within=section,name=Text]{textcell}",
      "    \\DeclareFloatingEnvironment[",
      "        fileext=frm,placement={!ht},",
      "        within=section,name=Text]{errorcell}",
      "",
      "    \\usepackage{listings} % a package for wrapping code in a box",
      "    \\usepackage[framemethod=tikz]{mdframed} % to fram code",
      ""
    ],
    "document_header_end": [
      "",
      "% make the code float work with cleverref",
      "\\crefname{codecell}{code}{codes}",
      "\\Crefname{codecell}{code}{codes}",
      "% make the text float work with cleverref",
      "\\crefname{textcell}{text}{texts}",
      "\\Crefname{textcell}{text}{texts}",
      "% make the text float work with cleverref",
      "\\crefname{errorcell}{error}{errors}",
      "\\Crefname{errorcell}{error}{errors}"
    ],
    "document_definitions": [
      "",
      "\\definecolor{codegreen}{rgb}{0,0.6,0}",
      "\\definecolor{codegray}{rgb}{0.5,0.5,0.5}",
      "\\definecolor{codepurple}{rgb}{0.58,0,0.82}",
      "\\definecolor{backcolour}{rgb}{0.95,0.95,0.95}",
      "",
      "\\lstdefinestyle{mystyle}{",
      "    commentstyle=\\color{codegreen},",
      "    keywordstyle=\\color{magenta},",
      "    numberstyle=\\tiny\\color{codegray},",
      "    stringstyle=\\color{codepurple},",
      "    basicstyle=\\ttfamily,",
      "    breakatwhitespace=false,",
      "    keepspaces=true,",
      "    numbers=left,",
      "    numbersep=10pt,",
      "    showspaces=false,",
      "    showstringspaces=false,",
      "    showtabs=false,",
      "    tabsize=2,",
      "    breaklines=true,",
      "    literate={\\-}{}{0\\discretionary{-}{}{-}},",
      "  postbreak=\\mbox{\\textcolor{red}{$\\hookrightarrow$}\\space},",
      "}",
      "",
      "\\lstset{style=mystyle}",
      "",
      "\\surroundwithmdframed[",
      "  hidealllines=true,",
      "  backgroundcolor=backcolour,",
      "  innerleftmargin=0pt,",
      "  innerrightmargin=0pt,",
      "  innertopmargin=0pt,",
      "  innerbottommargin=0pt]{lstlisting}",
      ""
    ],
    "notebook_input_code": [
      "",
      "((( draw_text(cell.metadata,cell.source,\"code\",",
      "\"language=Python,numbers=left,xleftmargin=20pt,xrightmargin=5pt,belowskip=5pt,aboveskip=5pt\") )))"
    ],
    "notebook_output_text": [
      "",
      "((( draw_text(cell.metadata,output.data['text/plain'] | strip_ansi,\"text\",",
      "\"language={},postbreak={},numbers=none,xrightmargin=7pt,breakindent=0pt,aboveskip=5pt,belowskip=5pt\") )))"
    ],
    "notebook_output_stream": [
      "",
      "((*- if cell.metadata.get(\"ipub\",{}).get(\"text\",{}).use_ansi : -*))",
      "((( draw_text(cell.metadata,output.text | ansi2listings(\"%\") ,\"text\",",
      "\"language={},postbreak={},numbers=none,xrightmargin=7pt,belowskip=5pt,aboveskip=5pt,breakindent=0pt,escapechar=\\%\") )))",
      "((*- else -*))",
      "((( draw_text(cell.metadata,output.text | strip_ansi ,\"text\",",
      "\"language={},postbreak={},numbers=none,xrightmargin=7pt,belowskip=5pt,aboveskip=5pt,breakindent=0pt\") )))",
      "((*- endif *))"
    ],
    "notebook_output_error": [
      "",
      "((( super() )))"
    ],
    "notebook_output_traceback": [
      "",
      "((( draw_text(cell.metadata,line | indent | strip_ansi,\"error\",",
      "\"language=Python,numbers=none,xrightmargin=5pt,belowskip=2pt,aboveskip=2pt\") )))"
    ],
    "jinja_macros": [
      "",
      "((* macro draw_text(meta,source,type,options) -*))",
      "",
      "((*- if meta.ipub: -*))",
      "",
      "((*- if meta.ipub[type] -*))",
      "",
      "((*- if meta.ipub[type].asfloat: -*))",
      "    ((*- if meta.ipub[type].placement: -*))",
      "        ((*- if meta.ipub[type].widefigure: -*))",
      "    \\begin{(((type)))cell*}[((meta.ipub[type].placement)))]",
      "        ((*- else -*))",
      "    \\begin{(((type)))cell}[(((meta.ipub[type].placement)))]",
      "        ((*- endif *))",
      "    ((*- else -*))",
      "        ((*- if meta.ipub[type].widefigure: -*))",
      "    \\begin{(((type)))cell*}",
      "        ((*- else -*))",
      "    \\begin{(((type)))cell}",
      "        ((*- endif *))",
      "    ((*- endif *))",
      "",
      "",
      "    ((* set captionfound = false *))",
      "",
      "    ((*- if meta.ipub[type].label: -*))",
      "         ((*- if resources.captions: -*))",
      "             ((*- if resources.captions[meta.ipub[type].label]: -*))",
      "                 \\caption{((( resources.captions[meta.ipub[type].label] )))}",
      "                 ((* set captionfound = true *))",
      "             ((*- endif *))",
      "         ((*- endif *))",
      "    ((*- endif *))",
      "",
      "",
      "    ((*- if captionfound == false -*))",
      "    ((*- if meta.ipub[type].caption: -*))",
      "    \\caption{((( meta.ipub[type].caption )))}",
      "    ((*- endif *))",
      "    ((*- endif *))",
      "",
      "((*- endif *))",
      "",
      "((*- if meta.ipub[type].label: -*))",
      "\\label{((( meta.ipub[type].label )))}",
      "((*- endif *))",
      "",
      "((*- if meta.ipub[type].format: -*))",
      "\\begin{lstlisting}[((( meta.ipub[type].format | dict_to_kwds(options) )))]",
      "((*- else -*))",
      "\\begin{lstlisting}[((( options )))]",
      "((*- endif *))",
      "((( source )))",
      "\\end{lstlisting}",
      "",
      "((*- if meta.ipub[type].asfloat: -*))",
      "\\end{(((type)))cell}",
      "((*- endif *))",
      "",
      "((*- endif *))",
      "",
      "((*- endif *))",
      "((*- endmacro *))"
    ]
  },
  "template": "latex-tplx"
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/std-standard_contents.latex-tpl.json
{
  "$schema": "../outline_schema/latex_tplx_schema.json",
  "identifier": "standard-standard_contents",
  "description": "with standard nbconvert input/output content",
  "segments": {
    "notebook_input": [
      "",
      " ((( super() )))"
    ],
    "notebook_input_code": [
      "",
      "    ((( cell.source | highlight_code(strip_verbatim=True, metadata=cell.metadata) )))",
      ""
    ],
    "notebook_input_markdown": [
      "",
      "    ((( cell.source | citation2latex | strip_files_prefix | convert_pandoc('markdown', 'json',extra_args=[]) | resolve_references | convert_pandoc('json','latex'))))",
      ""
    ],
    "notebook_output": [
      "",
      " ((( super() )))"
    ],
    "notebook_output_text": [
      "",
      "    \\begin{verbatim}",
      "((( output.data['text/plain'] )))",
      "    \\end{verbatim}"
    ],
    "notebook_output_error": [
      "",
      "    \\begin{Verbatim}[commandchars=\\\\\\{\\}]",
      "((( super() )))",
      "    \\end{Verbatim}"
    ],
    "notebook_output_traceback": [
      "",
      "((( line | indent | strip_ansi | escape_latex )))"
    ],
    "notebook_output_stream": [
      "",
      "    \\begin{Verbatim}[commandchars=\\\\\\{\\}]",
      "((( output.text | escape_latex | ansi2latex )))",
      "    \\end{Verbatim}"
    ],
    "notebook_output_latex": [
      "",
      " ((( output.data['text/latex'] | strip_files_prefix )))"
    ],
    "notebook_output_markdown": [
      "",
      "((( output.data['text/markdown'] | citation2latex | strip_files_prefix | convert_pandoc('markdown', 'latex'))))"
    ],
    "notebook_output_png": [
      "",
      "((( draw_figure(output.metadata.filenames['image/png']) )))"
    ],
    "notebook_output_jpg": [
      "",
      "((( draw_figure(output.metadata.filenames['image/jpeg']) )))"
    ],
    "notebook_output_svg": [
      "",
      "((( draw_figure(output.metadata.filenames['image/svg+xml']) )))"
    ],
    "notebook_output_pdf": [
      "",
      "((( draw_figure(output.metadata.filenames['application/pdf']) )))"
    ],
    "jinja_macros": [
      "",
      "% Draw a figure using the graphicx package.",
      "((* macro draw_figure(filename) -*))",
      "((* set filename = filename | posix_path *))",
      "((*- block figure scoped -*))",
      "    \\begin{center}",
      "    \\adjustimage{max size={0.9\\linewidth}{0.9\\paperheight}}{((( filename )))}",
      "    \\end{center}",
      "    { \\hspace*{\\fill} \\\\}",
      "((*- endblock figure -*))",
      "((*- endmacro *))",
      ""
    ]
  },
  "template": "latex-tplx"
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/std-standard_definitions.latex-tpl.json
{
  "$schema": "../outline_schema/latex_tplx_schema.json",
  "identifier": "standard-standard_definitions",
  "description": "with standard nbconvert definitions",
  "segments": {
    "document_definitions": [
      "",
      "",
      "% Pygments definitions",
      "((( resources.latex.pygments_definitions )))",
      "",
      "% ANSI colors",
      "\\definecolor{ansi-black}{HTML}{3E424D}",
      "\\definecolor{ansi-black-intense}{HTML}{282C36}",
      "\\definecolor{ansi-red}{HTML}{E75C58}",
      "\\definecolor{ansi-red-intense}{HTML}{B22B31}",
      "\\definecolor{ansi-green}{HTML}{00A250}",
      "\\definecolor{ansi-green-intense}{HTML}{007427}",
      "\\definecolor{ansi-yellow}{HTML}{DDB62B}",
      "\\definecolor{ansi-yellow-intense}{HTML}{B27D12}",
      "\\definecolor{ansi-blue}{HTML}{208FFB}",
      "\\definecolor{ansi-blue-intense}{HTML}{0065CA}",
      "\\definecolor{ansi-magenta}{HTML}{D160C4}",
      "\\definecolor{ansi-magenta-intense}{HTML}{A03196}",
      "\\definecolor{ansi-cyan}{HTML}{60C6C8}",
      "\\definecolor{ansi-cyan-intense}{HTML}{258F8F}",
      "\\definecolor{ansi-white}{HTML}{C5C1B4}",
      "\\definecolor{ansi-white-intense}{HTML}{A1A6B2}",
      "",
      "% commands and environments needed by pandoc snippets",
      "% extracted from the output of `pandoc -s`",
      "\\providecommand{\\tightlist}{%",
      "  \\setlength{\\itemsep}{0pt}\\setlength{\\parskip}{0pt}}",
      "\\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\\\\{\\}}",
      "% Add ',fontsize=\\small' for more characters per line",
      "\\newenvironment{Shaded}{}{}",
      "\\newcommand{\\KeywordTok}[1]{\\textcolor[rgb]{0.00,0.44,0.13}{\\textbf{{#1}}}}",
      "\\newcommand{\\DataTypeTok}[1]{\\textcolor[rgb]{0.56,0.13,0.00}{{#1}}}",
      "\\newcommand{\\DecValTok}[1]{\\textcolor[rgb]{0.25,0.63,0.44}{{#1}}}",
      "\\newcommand{\\BaseNTok}[1]{\\textcolor[rgb]{0.25,0.63,0.44}{{#1}}}",
      "\\newcommand{\\FloatTok}[1]{\\textcolor[rgb]{0.25,0.63,0.44}{{#1}}}",
      "\\newcommand{\\CharTok}[1]{\\textcolor[rgb]{0.25,0.44,0.63}{{#1}}}",
      "\\newcommand{\\StringTok}[1]{\\textcolor[rgb]{0.25,0.44,0.63}{{#1}}}",
      "\\newcommand{\\CommentTok}[1]{\\textcolor[rgb]{0.38,0.63,0.69}{\\textit{{#1}}}}",
      "\\newcommand{\\OtherTok}[1]{\\textcolor[rgb]{0.00,0.44,0.13}{{#1}}}",
      "\\newcommand{\\AlertTok}[1]{\\textcolor[rgb]{1.00,0.00,0.00}{\\textbf{{#1}}}}",
      "\\newcommand{\\FunctionTok}[1]{\\textcolor[rgb]{0.02,0.16,0.49}{{#1}}}",
      "\\newcommand{\\RegionMarkerTok}[1]{{#1}}",
      "\\newcommand{\\ErrorTok}[1]{\\textcolor[rgb]{1.00,0.00,0.00}{\\textbf{{#1}}}}",
      "\\newcommand{\\NormalTok}[1]{{#1}}",
      "",
      "% Additional commands for more recent versions of Pandoc",
      "\\newcommand{\\ConstantTok}[1]{\\textcolor[rgb]{0.53,0.00,0.00}{{#1}}}",
      "\\newcommand{\\SpecialCharTok}[1]{\\textcolor[rgb]{0.25,0.44,0.63}{{#1}}}",
      "\\newcommand{\\VerbatimStringTok}[1]{\\textcolor[rgb]{0.25,0.44,0.63}{{#1}}}",
      "\\newcommand{\\SpecialStringTok}[1]{\\textcolor[rgb]{0.73,0.40,0.53}{{#1}}}",
      "\\newcommand{\\ImportTok}[1]{{#1}}",
      "\\newcommand{\\DocumentationTok}[1]{\\textcolor[rgb]{0.73,0.13,0.13}{\\textit{{#1}}}}",
      "\\newcommand{\\AnnotationTok}[1]{\\textcolor[rgb]{0.38,0.63,0.69}{\\textbf{\\textit{{#1}}}}}",
      "\\newcommand{\\CommentVarTok}[1]{\\textcolor[rgb]{0.38,0.63,0.69}{\\textbf{\\textit{{#1}}}}}",
      "\\newcommand{\\VariableTok}[1]{\\textcolor[rgb]{0.10,0.09,0.49}{{#1}}}",
      "\\newcommand{\\ControlFlowTok}[1]{\\textcolor[rgb]{0.00,0.44,0.13}{\\textbf{{#1}}}}",
      "\\newcommand{\\OperatorTok}[1]{\\textcolor[rgb]{0.40,0.40,0.40}{{#1}}}",
      "\\newcommand{\\BuiltInTok}[1]{{#1}}",
      "\\newcommand{\\ExtensionTok}[1]{{#1}}",
      "\\newcommand{\\PreprocessorTok}[1]{\\textcolor[rgb]{0.74,0.48,0.00}{{#1}}}",
      "\\newcommand{\\AttributeTok}[1]{\\textcolor[rgb]{0.49,0.56,0.16}{{#1}}}",
      "\\newcommand{\\InformationTok}[1]{\\textcolor[rgb]{0.38,0.63,0.69}{\\textbf{\\textit{{#1}}}}}",
      "\\newcommand{\\WarningTok}[1]{\\textcolor[rgb]{0.38,0.63,0.69}{\\textbf{\\textit{{#1}}}}}",
      "",
      "",
      "% Define a nice break command that doesn't care if a line doesn't already",
      "% exist.",
      "\\def\\br{\\hspace*{\\fill} \\\\* }",
      "",
      "% Math Jax compatability definitions",
      "\\def\\gt{>}",
      "\\def\\lt{<}",
      ""
    ]
  },
  "template": "latex-tplx"
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/std-standard_article.latex-tpl.json
{
  "$schema": "../outline_schema/latex_tplx_schema.json",
  "identifier": "standard-standard_article",
  "description": "with standard nbconvert article setup",
  "segments": {
    "document_docclass": [
      "\\documentclass[11pt]{article}"
    ],
    "document_margins": [
      "",
      "\\usepackage{geometry} % Used to adjust the document margins",
      "% Slightly bigger margins than the latex defaults",
      "\\geometry{verbose,tmargin=1in,bmargin=1in,lmargin=1in,rmargin=1in}"
    ],
    "document_packages": [
      "",
      "",
      "\\usepackage[T1]{fontenc} % Nicer default font (+ math font) than Computer Modern for most use cases",
      "\\usepackage{mathpazo}",
      "\\usepackage{graphicx}",
      "\\usepackage{caption}",
      "\\usepackage{adjustbox} % Used to constrain images to a maximum size",
      "\\usepackage{xcolor} % Allow colors to be defined",
      "\\usepackage{enumerate} % Needed for markdown enumerations to work",
      "\\usepackage{amsmath} % Equations",
      "\\usepackage{amssymb} % Equations",
      "\\usepackage{textcomp} % defines textquotesingle",
      "% Hack from http://tex.stackexchange.com/a/47451/13684:",
      "\\AtBeginDocument{%",
      "    \\def\\PYZsq{\\textquotesingle}% Upright quotes in Pygmentized code",
      "}",
      "\\usepackage{upquote} % Upright quotes for verbatim code",
      "\\usepackage{eurosym} % defines \\euro",
      "\\usepackage[mathletters]{ucs} % Extended unicode (utf-8) support",
      "\\usepackage[utf8]{inputenc} % Allow utf-8 characters in the tex document",
      "\\usepackage{fancyvrb} % verbatim replacement that allows latex",
      "\\usepackage{grffile} % extends the file name processing of package graphics",
      "                        % to support a larger range",
      "% The hyperref package gives us a pdf with properly built",
      "% internal navigation ('pdf bookmarks' for the table of contents,",
      "% internal cross-reference links, web links for URLs, etc.)",
      "\\usepackage{hyperref}",
      "\\usepackage{longtable} % longtable support required by pandoc >1.10",
      "\\usepackage{booktabs}  % table support for pandoc > 1.12.2",
      "\\usepackage[inline]{enumitem} % IRkernel/repr support (it uses the enumerate* environment)",
      "\\usepackage[normalem]{ulem} % ulem is needed to support strikethroughs (\\sout)",
      "                            % normalem makes italics be italics, not underlines",
      "",
      "\\usepackage{todonotes} % to mark to-dos"
    ],
    "document_definitions": [
      "",
      "% Colors for the hyperref package",
      "\\definecolor{urlcolor}{rgb}{0,.145,.698}",
      "\\definecolor{linkcolor}{rgb}{.71,0.21,0.01}",
      "\\definecolor{citecolor}{rgb}{.12,.54,.11}",
      "",
      "% Basic figure setup, for now with no caption control since it's done",
      "% automatically by Pandoc (which extracts ![](path) syntax from Markdown).",
      "% We will generate all images so they have a width \\maxwidth. This means",
      "% that they will get their normal width if they fit onto the page, but",
      "% are scaled down if they would overflow the margins.",
      "\\makeatletter",
      "\\def\\maxwidth{\\ifdim\\Gin@nat@width>\\linewidth\\linewidth",
      "\\else\\Gin@nat@width\\fi}",
      "\\makeatother",
      "\\let\\Oldincludegraphics\\includegraphics",
      "% Set max figure width to be 80% of text width, for now hardcoded.",
      "\\renewcommand{\\includegraphics}[1]{\\Oldincludegraphics[width=.8\\maxwidth]{#1}}",
      "% Ensure that by default, figures have no caption (until we provide a",
      "% proper Figure object with a Caption API and a way to capture that",
      "% in the conversion process - todo).",
      "\\DeclareCaptionLabelFormat{nolabel}{}",
      "\\captionsetup{labelformat=nolabel}",
      ""
    ],
    "document_header_end": [
      "",
      "% clereref must be loaded after anything that changes the referencing system",
      "\\usepackage{cleveref}",
      "\\creflabelformat{equation}{#2#1#3}"
    ],
    "document_commands": [
      "",
      "% Prevent overflowing lines due to hard-to-break entities",
      "\\sloppy",
      "% Setup hyperref package",
      "\\hypersetup{",
      "    breaklinks=true,  % so long urls are correctly broken across lines",
      "    colorlinks=true,",
      "    urlcolor=urlcolor,",
      "    linkcolor=linkcolor,",
      "    citecolor=citecolor,",
      "    }",
      ""
    ],
    "document_title": [
      "",
      "\\title{((( resources.metadata.name | ascii_only | escape_latex )))}",
      "\\maketitle"
    ]
  },
  "template": "latex-tplx"
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/std-standard_packages.latex-tpl.json
{
  "$schema": "../outline_schema/latex_tplx_schema.json",
  "identifier": "standard-standard_packages",
  "description": "with standard nbconvert packages",
  "segments": {
    "document_packages": [
      "",
      "",
      "\\usepackage[T1]{fontenc} % Nicer default font (+ math font) than Computer Modern for most use cases",
      "\\usepackage{mathpazo}",
      "\\usepackage{graphicx}",
      "\\usepackage[skip=3pt]{caption}",
      "\\usepackage{adjustbox} % Used to constrain images to a maximum size",
      "\\usepackage[table]{xcolor} % Allow colors to be defined",
      "\\usepackage{enumerate} % Needed for markdown enumerations to work",
      "\\usepackage{amsmath} % Equations",
      "\\usepackage{amssymb} % Equations",
      "\\usepackage{textcomp} % defines textquotesingle",
      "% Hack from http://tex.stackexchange.com/a/47451/13684:",
      "\\AtBeginDocument{%",
      "    \\def\\PYZsq{\\textquotesingle}% Upright quotes in Pygmentized code",
      "}",
      "\\usepackage{upquote} % Upright quotes for verbatim code",
      "\\usepackage{eurosym} % defines \\euro",
      "\\usepackage[mathletters]{ucs} % Extended unicode (utf-8) support",
      "\\usepackage[utf8x]{inputenc} % Allow utf-8 characters in the tex document",
      "\\usepackage{fancyvrb} % verbatim replacement that allows latex",
      "\\usepackage{grffile} % extends the file name processing of package graphics",
      "                        % to support a larger range",
      "% The hyperref package gives us a pdf with properly built",
      "% internal navigation ('pdf bookmarks' for the table of contents,",
      "% internal cross-reference links, web links for URLs, etc.)",
      "\\usepackage{hyperref}",
      "\\usepackage{longtable} % longtable support required by pandoc >1.10",
      "\\usepackage{booktabs}  % table support for pandoc > 1.12.2",
      "\\usepackage[inline]{enumitem} % IRkernel/repr support (it uses the enumerate* environment)",
      "\\usepackage[normalem]{ulem} % ulem is needed to support strikethroughs (\\sout)",
      "                            % normalem makes italics be italics, not underlines",
      ""
    ]
  },
  "template": "latex-tplx"
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/std-in_out_prompts.latex-tpl.json
{
  "overwrite": [
    "notebook_output",
    "notebook_input_code"
  ],
  "$schema": "../outline_schema/latex_tplx_schema.json",
  "identifier": "standard-in_out_prompts",
  "description": "with in/out prompts",
  "segments": {
    "document_definitions": [
      "",
      "",
      "    % Exact colors from NB",
      "    \\definecolor{incolor}{rgb}{0.0, 0.0, 0.5}",
      "    \\definecolor{outcolor}{rgb}{0.545, 0.0, 0.0}",
      ""
    ],
    "notebook_input_code": [
      "",
      "    ((( add_prompt(cell.source | highlight_code(strip_verbatim=True, metadata=cell.metadata), cell, 'In ', 'incolor') )))",
      ""
    ],
    "notebook_output": [
      "",
      "        ((*- if resources.global_content_filter.include_output_prompt -*))",
      "            ((*- if type in ['text/plain'] *))",
      "((( add_prompt(output.data['text/plain'] | escape_latex, cell, 'Out', 'outcolor') )))",
      "            ((* else -*))",
      "\\texttt{\\color{outcolor}Out[{\\color{outcolor}((( cell.execution_count )))}]:}((( super() )))",
      "            ((*- endif -*))",
      "        ((*- endif -*))",
      ""
    ],
    "jinja_macros": [
      "",
      "% Purpose: Renders an output/input prompt",
      "((* macro add_prompt(text, cell, prompt, prompt_color) -*))",
      "    ((*- if cell.execution_count is defined -*))",
      "    ((*- set execution_count = \"\" ~ (cell.execution_count | replace(None, \" \")) -*))",
      "    ((*- else -*))",
      "    ((*- set execution_count = \" \" -*))",
      "    ((*- endif -*))",
      "    ((*- set indention =  \" \" * (execution_count | length + 7) -*))",
      "\\begin{Verbatim}[commandchars=\\\\\\{\\}]",
      "((( text | add_prompts(first='{\\color{' ~ prompt_color ~ '}' ~ prompt ~ '[{\\\\color{' ~ prompt_color ~ '}' ~ execution_count ~ '}]:} ', cont=indention) )))",
      "\\end{Verbatim}",
      "((*- endmacro *))",
      ""
    ]
  },
  "template": "latex-tplx"
}

=== chrisjsewell/ipypublish/ipypublish/templates/segments/ipy-biblio_natbib.latex-tpl.json
{
  "$schema": "../outline_schema/latex_tplx_schema.json",
  "identifier": "ipypublish-biblio_natbib",
  "description": "with the main ipypublish bibliography",
  "segments": {
    "document_packages": [
      "",
      "% bibliography formatting",
      "\\usepackage[numbers, square, super, sort&compress]{natbib}",
      "% hyperlink doi's",
      "\\usepackage{doi}"
    ],
    "document_bibliography": [
      "",
      "((*- if nb.metadata.ipub: -*))",
      "((*- if nb.metadata.ipub.bibliography: -*))",
      "((* set filename = nb.metadata.ipub.bibliography | strip_ext | posix_path *))",
      "",
      "% sort citations by order of first appearance",
      "\\bibliographystyle{unsrtnat}",
      "\\bibliography{((( filename )))}",
      "",
      "((*- endif *))",
      "((*- endif *))"
    ]
  },
  "template": "latex-tplx"
}
